
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api

  api:
    build: ./backend
    ports:
      - 8000:8000
    environment:
      # to be replaced with an actual mongo atlas URL
      DB_URL: mongodb+srv://<username>:<password>@<cluster>.mongodb.net/anime?retryWrites=true&w=majority
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync